### ISSUE TITLE
Loading images

### ISSUE THREAD

**Issue by aligit** [Foxandxss/GermanWords-ng1-webpack#5]
With this setup, the images don't get loaded in the template.

``` html
<img src="../../../logo.png" />
```

Any idea why images are not loaded? I have also tried

``` html
<img src="file!../../../logo.png" />
```

but does not show up neither.

It could be great if you can also add an image to the example.

**Comment by Foxandxss** [comment]
https://github.com/Foxandxss/angular-webpack-workflow/issues/5

**Comment by aligit** [comment]
great!
Thanks
